# Generated by Django 6.1.1 on 2026-09-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspace',
            old_name='price_per_hour',
            new_name='price_per_minute',
        ),
    ]
