# Generated by Django 6.1.1 on 2026-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_rename_price_per_hour_parkingspace_price_per_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
