# Generated by Django 6.1.1 on 2026-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_booking_otp_booking_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
