# Generated by Django 6.1.1 on 2026-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='occupied_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
